-- 코드를 입력하세요

SELECT book_id,AUTHOR_NAME,to_char(PUBLISHED_DATE,'YYYY-MM-DD') 	PUBLISHED_DATE from BOOK B join AUTHOR A on B.AUTHOR_ID = A.AUTHOR_ID where B.CATEGORY ='경제' order by PUBLISHED_DATE asc;
